# Deploys the 3 e-commerce services:
# web-storefront (LoadBalancer)
# inventory-service (ClusterIP)
# payment-service (ClusterIP)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-storefront-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-storefront
  template:
    metadata:
      labels:
        app: web-storefront
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: web-storefront
          image: poornavscalerfinal.azurecr.io/web-storefront:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-storefront
spec:
  type: LoadBalancer # This is the only public-facing service
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: web-storefront
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: inventory-service
          image: poornavscalerfinal.azurecr.io/inventory-service:v1
          ports:
            - containerPort: 8080
          env:
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service/api"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: ClusterIP # Internal only
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: inventory-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: payment-service
          image: poornavscalerfinal.azurecr.io/payment-service:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP # Internal only
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: payment-service
